# Generated by Django 3.2.9 on 2021-11-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='created_by',
        ),
    ]
