# Generated by Django 3.2.9 on 2021-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_alter_messages_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
